apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x00nhgolp-java-springboot
  janus-idp.io/tekton: x00nhgolp-java-springboot
  backstage.io/kubernetes-id: x00nhgolp-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x00nhgolp-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
